### ISSUE TITLE
Cannot install v1.8.1

### ISSUE THREAD

**Issue by johnpash** [prismicio/ruby-kit#108]
I've noticed that v.1.8.1 of this gem was released in January (2 months+) but it is not available on Rubygems https://rubygems.org/gems/prismic.io

Did someone maybe forget to push the --tags? I'm not very familiar with what mechanism actually makes the next version available. So I apologise if I'm doing something stupid!

Anyhow, the end effect is that `bundle install prismic.io` with no other dependencies in a Gemfile with 
`source "https://rubygems.org"`
installs version 1.8.0, not 1.8.1

**Comment by filippoliverani** [comment]
As far as I can see the lastest released has not be loaded to Rubygems, if you want to use the Github tag you have to do something like:
```ruby
gem 'prismic.io', github: 'prismicio/ruby-kit', tag: 'v1.8.1', require: 'prismic
```
@MarcMcIntosh can you please push the 1.8.1 release to Rubygems 🙏 ?

**Comment by MarcMcIntosh** [comment]
Hi, thanks for reminding me about this. @johnpash and @filippoliverani 

1.8.1 is now released :)
