### ISSUE TITLE
Recent merge breaks specs?

### ISSUE THREAD

**Issue by dhainlin** [prismicio/ruby-kit#51]
Am working on a potential PR (to add option for null api cache to aid ruby projects that use VCR) and after pull of recent merge (3285f6d633886c9f4baed40b456703e0c86ce131), specs break because of undefined local variable or method `token_cache' for Prismic::API:Class at line 128 of lib/prismic/api.rb

**Comment by erwan** [comment]
Yes indeed, the build was broken. It's fixed, sorry for the trouble!
