### ISSUE TITLE
Missing data when doing .as_json

### ISSUE THREAD

**Issue by cabouffard** [prismicio/ruby-kit#55]
Hey, 

When I try to see my structured text data as json it shows it like that
```
["bio", {"blocks"=>[{"text"=>"Italic Test", "spans"=>[], "label"=>nil}, {"text"=>"Preformatted test", "spans"=>[], "label"=>nil}, {"text"=>"Bold Test", "spans"=>[{"start"=>0, "end"=>9}], "label"=>nil}]}]
```

As you can see, I does not show all the informations (span types, text type) like the api page says it is suppose to return. 

Am i doing this incorrectly?
```
@documents.each do |doc|
  = doc.as_json
```

Thanks!

**Comment by erwan** [comment]
Hi,

The API page describes what the REST API returns, but when you use the kit it's transforming the data into a Ruby object that let you serialize directly to HTML.

The best way to use the kit for StructuredText fields is to use it to generate HTML. If for some reason you need to get the original data, the best is to simply make a REST call without using the kit helpers.
