### ISSUE TITLE
Lost of data after modifying a Mask

### ISSUE THREAD

**Issue by cabouffard** [prismicio/ruby-kit#58]
Hi, 

We have over 50 documents under a certain mask. One of the field was not being used by anything so we have decided to remove it from the mask. 

Since then, I am unable to retrieve the datas from that mask. All the documents are being shown in the Prismic Dashboard. I am also able to retrieve my content from `{my_prismic_url}/api` by doing this simple query `[:d = at(document.type, "my-mask")]`. The same query is being used in our ruby implementation. 

Once I updated a field of a document of my mask, I was able to retrieve that document. This is why I suspect the problem comes from the caching of the gem. 

I have tried to setting the cache option to `Prismic::BasicNullCache.new` with no effects. 

Could you guys give me a hand to figure out where the issue would come from? Thanks!

**Comment by erwan** [comment]
Hi,

The cache stores everything in memory, so if you still don't see the documents after a restart the problem is not linked to the cache.

Could you open a support ticket with the name of your repository and the mask that poses problem?

**Comment by erwan** [comment]
It appear to be simply due to pagination
