### ISSUE TITLE
Support "Slices" fragment type

### ISSUE THREAD

**Issue by CHH** [prismicio/ruby-kit#59]
Currently it looks like the ruby-kit doesn't support fragments of type "Slices". An error is thrown when a document is retrieved which contains such a fragment.

**Comment by erwan** [comment]
Hi,

Slices are supported. We recently added support for Separator and didn't cut a release yet. Maybe that's why you're getting an error?

**Comment by CHH** [comment]
Ok, I looked at it about a week ago. Didn’t try it since then.

I will try it again tomorrow.

**Comment by smd686s** [comment]
Hi @CHH.  Any luck here?  I've been using the Master version of the kit and use slices quite a bit.

**Comment by smd686s** [comment]
Close?

**Comment by dohzya** [comment]
Close 🙂
