### ISSUE TITLE
Additional Operators

### ISSUE THREAD

**Issue by smd686s** [prismicio/ruby-kit#61]
The Prismic documentation lists a few operators that do not have corresponding methods in Prismic::Predicates (https://github.com/prismicio/ruby-kit/blob/master/lib/prismic/predicates.rb).  Without looking to closely, I see the following aren't available:

[:d = has(my.blog-post.author)]
[:d = missing(my.blog-post.author)]

Thoughts?

**Comment by erwan** [comment]
Yes indeed, those have been added more recently than the others and they haven't been added to the helpers yet. You can still use them by passing the query as a string in the meantime.

**Comment by erwan** [comment]
thanks for the PR!
