### ISSUE TITLE
API V2 Support?

### ISSUE THREAD

**Issue by tavour-frank** [prismicio/ruby-kit#85]
Currently tinkering with prismic on a rails app, and looks like this gem only supports api V1. I can't find any documentation regarding the change diff between API versions - are there any plans to update this gem to support v2 as well as v1?

**Comment by matthewlein** [comment]
No API v2 support is a dealbreaker for me, since the v1 responses can't be rendered with the react rich text library.

It also took me a few hours to even realize that my error:
```
Type  is unknown, fragment was skipped; perhaps you should update your prismic.io gem?
Traceback (most recent call last):
        1: from (irb):1
NoMethodError (undefined method `[]' for nil:NilClass)
```
was coming from being pointed at a v2 api url...

**Comment by MarcMcIntosh** [comment]
Hi @tavour-frank there's a short article on some of the difference between api v1 and v2 here https://user-guides.prismic.io/en/articles/1403345-difference-between-api-v1-v2

Also one of the differences not mentioned in the article is that v1 includes a type property for each field,

v1
```
"data": {
  "doc": {
     "title": {
         "type": "StructuredText",
         "value": [{
             "type": "heading1",
             "text": "Installing meta-micro",
             "spans": [ ]
         }]
     },
  }
}
```

v2 
```
"data": {
  "doc": {
     "title": [{
           "type": "heading1",
           "text": "Installing meta-micro",
           "spans": [ ]
      }]
  }
}
```
