### ISSUE TITLE
Support the Boolean field inside Slices

### ISSUE THREAD

**Issue by jamesmosier** [prismicio/ruby-kit#91]
With the release of the [boolean field](https://user-guides.prismic.io/en/articles/3456034-boolean-field) and [slices](https://user-guides.prismic.io/en/articles/383933-slices) it would be great to see these supported together. 

Currently when a boolean field is inside a slice the method `api.getByID` errors out with a generic ```undefined method `call' for nil:NilClass``` error.

**Comment by reinho** [comment]
Further, this bug is not just affecting slices but also queries that return multiple documents when they contain boolean fields.

Until this feature is added, booleans are not usable in Ruby.

**Comment by sarco3t** [comment]
I was able to fix the issue by overriding prismic parsers list and adding boolean parser.

**Comment by gdotdesign** [comment]
I've ended up doing this:

```ruby
Prismic::JsonParser.parsers['Boolean'] = ->(json) { json['value'] }
```

**Comment by Duaner** [comment]
We did a PR to support that. https://github.com/prismicio/ruby-kit/pull/95

Closing this issue.
